### ISSUE TITLE
Markdown or WYSIWYG

### ISSUE THREAD

**Issue by thangngoc89** [Larask/gist#2]
Which kind of editor will we support? 

If Markdown, we will use http://parsedown.org/ for Markdown parsing.

**Comment by luuhoangnam** [comment]
Of course, it's **Markdown**

**Comment by thangngoc89** [comment]
@luuhoangnam okie. :+1: I like it too. How about front-end editor? Is there any good one?

IMO: I like ghost front-end editor and there is a clone in the market ( http://ghosditor.herokuapp.com/ )
Or Stack edit : https://github.com/benweet/stackedit

**Comment by luuhoangnam** [comment]
@thangngoc89 no, our main object is snippets, not a post or article. Why do you think we will use a text editor (in-browser)? I think we should use a code editor like http://ace.c9.io/#nav=about

**Comment by thangngoc89** [comment]
@luuhoangnam Am I wrong or Github Gist using Ace Editor too? So we will use ace editor for our first version. But we will decouple it from Gist to let's user choose which edtior they should use. In my website, I'll to use a WYSIWYG editor (my users have no idea what markdown is)

**Comment by luuhoangnam** [comment]
No, you was not wrong but like i said, "we should". Don't try to combine all-in-one product. We make a simple service for code/text snippets, not articles. A second reason is post/article and snippets is too difference. Do you want to make a blog or gist service, so you will know how to choose between WYSIWYG editor or code editor??? I need to know your decision.

**Comment by thangngoc89** [comment]
@luuhoangnam Sound fair. We will make a simple service for code/text snippets. NOT articles. I think that easier for develop and maintain.
